---
- name: My first playbook
  hosts: webservers
  become: true
  tasks:
  - name: Install apache httpd (state=present is optional)
    apt:
      name: apache2
      state: absent
  - name: Install docker.io
    apt:
      update_cache: yes
      name: docker.io
      state: present
  - name: Install pip3
    apt:
      name: python3-pip
      state: present
  - name: Install docker
    pip:
      name: docker
      state: present
  - name: Install dvwa
    docker_container:
      name: dvwa
